name: digital_calculator
description: A neumorphic themed digital calculator which has keyboard and dark mode support
publish_to: 'none'
version: 1.0.1+2
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_native_splash: ^2.2.16
  math_expressions: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Digital Numbers
      fonts:
        - asset: assets/fonts/DigitalNumbers-Regular.ttf

flutter_native_splash:
  color: "#F1F3F6"
  color_dark: "#24272C"
  image: assets/icon.png
  android_12:
    image: assets/icon.png
    color: "#F1F3F6"
    image_dark: assets/icon.png
    color_dark: "#24272C"
