name: digital_calculator
description: A neumorphic themed digital calculator which has keyboard and dark mode support
publish_to: 'none'
version: 1.1.0+5
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Digital Numbers
      fonts:
        - asset: assets/fonts/DigitalNumbers-Regular.ttf
