name: digital_calculator
description: A neumorphic themed digital calculator which has keyboard and dark mode support
publish_to: 'none'
version: 1.2.0+7
environment:
  sdk: ^3.7.0
  flutter: 3.29.3
dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.7.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Digital Numbers
      fonts:
        - asset: assets/fonts/DigitalNumbers-Regular.ttf
